name: Docker Android Feature Test

on:
  push:
    branches: ['feature/*']

env:
  DOCKER_IMAGE: ${{ secrets.DOCKER_HUB_USERNAME }}/docker-android

jobs:

  # Builds a test image.
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v4
        with:
          driver: docker-container
      - name: Login to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build minimal Docker image
        uses: docker/build-push-action@v7
        with:
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ env.DOCKER_IMAGE }}:test
          cache-from: type=gha,scope=test
          cache-to: type=gha,mode=max,scope=test
          build-args: INSTALL_ANDROID_SDK=0
